# Generated by Django 4.2.4 on 2023-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemstone',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Color(s)'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
