# Generated by Django 4.2.4 on 2023-09-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_rename_descripton_gemstone_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
