# Generated by Django 4.2.4 on 2023-09-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0003_clarity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clarity',
            new_name='GemstoneClarity',
        ),
    ]
