# Generated by Django 4.2.4 on 2023-09-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0004_rename_clarity_gemstoneclarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gemstoneclarity',
            options={'verbose_name_plural': 'Gemsonte clarities'},
        ),
        migrations.AddField(
            model_name='gemstone',
            name='clarity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='gemstones', to='treasure.gemstoneclarity'),
        ),
    ]
