# Generated by Django 4.2.4 on 2023-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0005_alter_gemstoneclarity_options_gemstone_clarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstone',
            name='color',
            field=models.CharField(blank=True, max_length=128, verbose_name='Color(s)'),
        ),
        migrations.AlterField(
            model_name='gemstone',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
