# Generated by Django 4.2.4 on 2023-09-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0006_gemstone_color_alter_gemstone_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gemstoneclarity',
            options={'verbose_name_plural': 'Gemstone clarities'},
        ),
    ]
